### ISSUE TITLE
Using canonical sUtra-numbers

### ISSUE THREAD

**Issue by vvasuki** [aupasana/ashtadhyayi#13]
This refers to https://github.com/sanskrit-coders/stardict-sanskrit/issues/21: अजित, अत्राऽपि सूत्रसङ्ख्यापरिवर्तनम् अनुमन्यसे वा? तेनैव सौकर्यम् भवतीति मन्ये…

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit/ashtadhyayi/issues handles it separately. Closing this issue.
