### ISSUE TITLE
Missing pada-6.2 in tattvabodhini

### ISSUE THREAD

**Issue by drdhaval2785** [aupasana/ashtadhyayi#2]
While running the code to correct hr,hy issues, I stumbled upon a missing folder in tattvabodhini namely pada 6.2
Please have a look at it.

**Comment by aupasana** [comment]
IIRC, the sansknet source location had broken links to these files when I pulled them many years ago.  We'll either have to find someone else that has these files, or manually typeset the entire pada.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit/ashtadhyayi/issues handles it separately. Closing this issue.
